/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DatetimePicker {
    'currDate': Date;
    'onDayClick': (date: Date) => Promise<string>;
    'toggleCalendar': () => Promise<boolean>;
  }
}

declare global {


  interface HTMLDatetimePickerElement extends Components.DatetimePicker, HTMLStencilElement {}
  var HTMLDatetimePickerElement: {
    prototype: HTMLDatetimePickerElement;
    new (): HTMLDatetimePickerElement;
  };
  interface HTMLElementTagNameMap {
    'datetime-picker': HTMLDatetimePickerElement;
  }
}

declare namespace LocalJSX {
  interface DatetimePicker {
    'currDate'?: Date;
  }

  interface IntrinsicElements {
    'datetime-picker': DatetimePicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'datetime-picker': LocalJSX.DatetimePicker & JSXBase.HTMLAttributes<HTMLDatetimePickerElement>;
    }
  }
}


